# Generated by Django 4.2.7 on 2024-02-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Sname',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Sprincipal',
            new_name='sprincipal',
        ),
    ]
